# .github/workflows/simple_tests.yml
# Fixed CI/CD pipeline with all dependencies

name: Simple Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Get the code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # Step 2: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    # Step 3: Install ALL dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit requests pandas plotly ollama
        pip install pytest selenium webdriver-manager requests-mock pytest-cov
    
    # Step 4: Install Chrome for Selenium
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable xvfb
    
    # Step 5: Run unit tests (skip ollama-dependent tests)
    - name: Run unit tests
      run: |
        pytest test_backend.py -v -k "not ollama"
      env:
        SKIP_OLLAMA_TESTS: "true"
    
    # Step 6: Run UI tests (headless)
    - name: Run UI tests
      run: |
        # Start virtual display for headless browser
        export DISPLAY=:99
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 2
        
        # Run Selenium tests
        pytest test_ui.py -v
      env:
        DISPLAY: ":99"